version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped

    env_file:
      - ./env/redis.env

    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]

    ports:
      - "6379:6379"

    volumes:
      - ./data:/data

    # Memory limits (optional for dev/light usage)
    mem_limit: 1g
    memswap_limit: 1g
    shm_size: 256m
