version: "3.9"

services:
  mongo:
    image: mongo:7.1
    container_name: mongo
    restart: unless-stopped

    env_file:
      - ./env/mongo.env

    ports:
      - "27017:27017"

    volumes:
      - ./data:/data/db

    # Memory limits for dev / light usage
    mem_limit: 2g
    memswap_limit: 2g
    shm_size: 512m

    command: ["--auth"]
