version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2025-12-18T22-00-00Z
    container_name: minio
    restart: unless-stopped

    env_file:
      - ./env/minio.env

    # Command to start server
    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console

    volumes:
      - ./data:/data

    # Memory limits (optional for dev/light usage)
    mem_limit: 1g
    memswap_limit: 1g
    shm_size: 256m
